### ISSUE TITLE
Function does not return full number of latitudes

### ISSUE THREAD

**Issue by lteckentrup** [PedroLormendez/jcclass#1]
Hi,
 
I tried your package on a regional subset, and after this didn't work I tried your example file (`era5_daily_lowres.nc`) - for both files, calling `cts_27 = jc(filename).classification()` returns an DataArray with the correct number of timesteps and longitudes, but latitudes go missing? With your example file for example has `time: 31, latitude: 180, longitude: 360 `but `cts_27` gives `time: 31, lat: 160, lon: 360`. Is this on purpose?

**Comment by PedroLormendez** [comment]
Hi Lina,

Many thanks for reaching out. Based on your comment, this is no error. The JC Classification is not able to compute the circulation types above the +/- 80º latitude. Since the method uses +/- 10º of data towards north/south of the relative central point, you will always "miss" those points. This would also apply if you choose a smaller regions (instead of the globe) where you would lose 12.5º longitude points east and west of your original MSLP data. When computing the circulation types, always account for this extra spacing. I hope this helps.

**Comment by lteckentrup** [comment]
Oh ok! Thank you so much for clarifying! Should have thought about it more carefully before posting the question:)
